---
name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
template: |
  # Changelog
  $CHANGES

  See details of [all code changes](https://github.com/github/cleanowners/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION) since previous release

categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance'
    labels:
      - 'infrastructure'
      - 'automation'
      - 'documentation'
      - 'dependencies'
      - 'revert'
  - title: '🏎 Performance'
    label: 'performance'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
version-resolver:
  major:
    labels:
      - 'breaking'
  minor:
    labels:
      - 'enhancement'
  patch:
    labels:
      - 'bug'
      - 'maintenance'
      - 'documentation'
  default: patch
autolabeler:
  - label: 'automation'
    title:
      - '/^(build|ci|perf|refactor|test).*/i'
  - label: 'enhancement'
    title:
      - '/^(chore|style).*/i'
  - label: 'documentation'
    title:
      - '/^docs.*/i'
  - label: 'feature'
    title:
      - '/^feat.*/i'
  - label: 'fix'
    title:
      - '/^fix.*/i'
  - label: 'infrastructure'
    title:
      - '/^infrastructure.*/i'
  - label: 'revert'
    title:
      - '/^revert.*/i'
