issuer: https://token.actions.githubusercontent.com
subject_pattern: "repo:github-community-projects/cleanowners:pull_request"
claim_pattern:
  job_workflow_ref: "github-community-projects/cleanowners/.github/workflows/update-uv-lock.yml@.*"

permissions:
  contents: write
